INSERT INTO categories (id,name,slug,tagline,description,accent,image_url,sort_order) VALUES
(1,'Masalas','masalas','Stone-ground the morning we pack them','Whole spices, dry-roasted in an iron kadai until the kitchen smells like it should, then ground coarse. No colour, no anti-caking agent, no filler rava. They clump in humidity because there is nothing in them to stop it.','chilli','/images/categories/masalas.webp',1),
(2,'Pickles','pickles','Twenty-one days on the terrace','Cut, salted, sun-cured, and only then met with oil and spice. Every batch is tied to a season and a specific tree, so no two years taste identical. Use a dry spoon and they will outlive the jar.','turmeric','/images/categories/pickles.webp',2),
(3,'Fresh Batters','fresh-batters','Ground at night, delivered cold by morning','Sona masoori and urad dal, soaked separately, wet-ground, and left to ferment overnight. Shipped chilled within a day of grinding, because the whole point is that it is fresh.','leaf','/images/categories/fresh-batters.webp',3),
(4,'Snacks','snacks','Fried in small batches, never yesterday''s','The tin on top of the fridge that everyone raids at four o''clock. Fried the day it ships, drained properly, and packed while still warm enough to fog the bag.','indigo','/images/categories/snacks.webp',4),
(5,'Sweets','sweets','Ghee-heavy and unapologetic','Made to order, never stocked. Which means a day or two longer to reach you and a texture that has not had time to go hard.','rose','/images/categories/sweets.webp',5);

INSERT INTO products (id,name,slug,category_id,short_description,description,ingredients,shelf_life,price,compare_at_price,unit_label,sku,stock_qty,spice_level,is_veg,is_featured,is_active,image_url,gallery,pairs_with,rating_avg,rating_count) VALUES
(1,'Chicken Sukka Masala','chicken-sukka-masala',1,'Mangalorean sukka blend — byadgi chilli, roasted coconut, a hard sear of coriander.','This is the coastal Karnataka sukka masala, the dry one, where the coconut is roasted almost to the edge of burnt before it goes into the grinder. Byadgi chillies give it the colour without the assault; the heat comes from guntur that we add by hand, a smaller measure. Half a kilo of chicken takes three heaped spoons. Finish with curry leaves in coconut oil and do not add water — sukka means dry.','Byadgi chilli, guntur chilli, coriander seed, roasted coconut, cumin, black pepper, fenugreek, mustard, turmeric, curry leaf, tamarind, rock salt','6 months, airtight, away from the stove',249.00,299.00,'200 g','KR-MAS-001',48,3,FALSE,TRUE,TRUE,'/images/products/chicken-sukka-masala.webp','["/images/products/chicken-sukka-masala.webp", "/images/categories/masalas.webp"]','Neer dosa, ghee rice, or plain kori roti',4.67,3),
(2,'Chicken Fry Masala','chicken-fry-masala',1,'The Sunday-afternoon fry masala. Sticks to the meat, crisps in the pan.','Coarser than the sukka, and built to cling. Rub it into chicken with curd and lemon, rest it for an hour, then shallow-fry until the edges catch. There is a little besan in the grind, which is what gives you the crust — the same trick every aunty uses and none of them admit to.','Kashmiri chilli, coriander seed, cumin, black pepper, garlic, ginger, roasted gram flour, garam masala, turmeric, salt','6 months, airtight',229.00,NULL,'200 g','KR-MAS-002',51,2,FALSE,TRUE,TRUE,'/images/products/chicken-fry-masala.webp','["/images/products/chicken-fry-masala.webp", "/images/categories/masalas.webp"]','Onion rings, lime, and a plate you can hold in one hand',4.00,1),
(3,'Fish Fry Masala','fish-fry-masala',1,'Tamarind-forward and rava-friendly. Built for pomfret, bangda and anything with a spine.','Coastal fish fry lives or dies on the sourness, so this one leans hard on tamarind and ajwain rather than more chilli. Make a thick paste with water, coat the fish, leave it twenty minutes, press into rava and shallow-fry in coconut oil. Works just as well on prawns.','Byadgi chilli, tamarind, coriander seed, ajwain, turmeric, garlic, black pepper, fenugreek, asafoetida, salt','6 months, airtight',239.00,279.00,'200 g','KR-MAS-003',40,2,FALSE,FALSE,TRUE,'/images/products/fish-fry-masala.webp','["/images/products/fish-fry-masala.webp", "/images/categories/masalas.webp"]','Rava coating, coconut oil, raw onion',4.00,1),
(4,'Sambar Masala','sambar-masala',1,'Roasted dal in the grind, not just spice. One spoon per serving is plenty.','Most shop sambar powder is chilli and coriander with the volume turned up. This one has channa dal and urad dal roasted into it, which is where the body comes from — you need less of it, and the sambar thickens without a cornflour trick. Add it after the dal and vegetables are cooked, never at the tempering stage.','Coriander seed, byadgi chilli, channa dal, urad dal, toor dal, fenugreek, cumin, black pepper, curry leaf, asafoetida, turmeric','8 months, airtight',189.00,NULL,'250 g','KR-MAS-004',75,1,TRUE,TRUE,TRUE,'/images/products/sambar-masala.webp','["/images/products/sambar-masala.webp", "/images/categories/masalas.webp"]','Drumstick, small onions, and a hot idli',5.00,1),
(5,'Mango Pickle','mango-pickle',2,'Raw totapuri, cut with the stone in, cured twenty-one days in the sun.','Made once a year, in May, from totapuri mangoes cut so the stone stays attached to the piece — that is where the flavour hides. Salted and sun-cured on the terrace for three weeks before the mustard and chilli go in, then topped with gingelly oil until the pieces are fully under. Sharp on day one, rounder by month three.','Raw mango, gingelly oil, red chilli powder, mustard, fenugreek, turmeric, asafoetida, rock salt','12 months. Dry spoon only.',279.00,329.00,'400 g','KR-PIC-001',36,3,TRUE,TRUE,TRUE,'/images/products/mango-pickle.webp','["/images/products/mango-pickle.webp", "/images/categories/pickles.webp"]','Curd rice. There is no second answer.',5.00,3),
(6,'Lemon Pickle','lemon-pickle',2,'No oil, no water. Just lemon, salt, chilli and four months of waiting.','The one your grandmother keeps for when someone is unwell. Lemons are quartered, packed in rock salt, and left until the skins go soft and translucent — about four months — before chilli and a mustard temper join in. Nothing is added to preserve it because the salt already did that job.','Lemon, rock salt, red chilli powder, mustard, fenugreek, turmeric','18 months. Gets better, not worse.',249.00,NULL,'400 g','KR-PIC-002',44,2,TRUE,FALSE,TRUE,'/images/products/lemon-pickle.webp','["/images/products/lemon-pickle.webp", "/images/categories/pickles.webp"]','Curd rice, dal rice, or straight off the spoon',5.00,1),
(7,'Garlic Pickle','garlic-pickle',2,'Whole peeled cloves, slow-cooked soft in gingelly oil and tamarind.','Peeling this much garlic by hand is the reason we only make it twice a year. The cloves are cooked whole in gingelly oil on the lowest flame until they lose their raw bite and turn almost sweet, then finished with tamarind and chilli. Eat a clove whole; do not chop it.','Garlic, gingelly oil, tamarind, red chilli powder, jaggery, mustard, fenugreek, salt','12 months. Dry spoon only.',269.00,NULL,'300 g','KR-PIC-003',28,3,TRUE,FALSE,TRUE,'/images/products/garlic-pickle.webp','["/images/products/garlic-pickle.webp", "/images/categories/pickles.webp"]','Chapati, curd rice, or a very plain khichdi',0.00,0),
(8,'Dosa Batter','dosa-batter',3,'Sona masoori and urad, wet-ground and fermented overnight. Ships cold.','Rice and urad dal soaked separately for six hours, ground wet in a stone grinder — not a mixie, the heat ruins it — and left to ferment overnight. It arrives chilled and slightly risen. Stir once, thin it with a splash of water, and keep the tawa hotter than feels right. Use within four days; keep it refrigerated the whole time.','Sona masoori rice, urad dal, fenugreek, salt, water','4 days refrigerated. It is a live batter.',99.00,NULL,'1 kg pouch','KR-FRS-001',52,0,TRUE,TRUE,TRUE,'/images/products/dosa-batter.webp','["/images/products/dosa-batter.webp", "/images/categories/fresh-batters.webp"]','Coconut chutney and any of our sambar masala',4.50,2),
(9,'Idli Batter','idli-batter',3,'Idli rice, thicker grind, more urad. Rises in the steamer, not on the counter.','Same overnight ferment as the dosa batter but ground thicker, with parboiled idli rice and a higher share of urad dal. That ratio is the entire difference between an idli that stays soft an hour later and one that turns into a coaster. Do not stir it flat before steaming — fold it gently.','Parboiled idli rice, urad dal, fenugreek, salt, water','4 days refrigerated',99.00,NULL,'1 kg pouch','KR-FRS-002',55,0,TRUE,FALSE,TRUE,'/images/products/idli-batter.webp','["/images/products/idli-batter.webp", "/images/categories/fresh-batters.webp"]','Molaga podi, sesame oil, and no cutlery',0.00,0),
(10,'Banana Chips','banana-chips',4,'Nendran, sliced into the oil itself, fried in coconut oil. Salted while hot.','Kerala-style. Raw nendran bananas are sliced directly over the wok so the pieces hit hot coconut oil within a second of being cut — that is why they stay pale gold instead of browning. Salt water is flicked in at the end, which spits alarmingly and is the only way to get salt to stick. Nothing else goes in.','Raw nendran banana, coconut oil, salt, turmeric','45 days, sealed',149.00,179.00,'250 g','KR-SNK-001',90,0,TRUE,TRUE,TRUE,'/images/products/banana-chips.webp','["/images/products/banana-chips.webp", "/images/categories/snacks.webp"]','Filter coffee at 4pm',5.00,1),
(11,'Chakli','chakli',4,'Hand-pressed spirals of rice and roasted gram. Snaps, never bends.','Rice flour and roasted gram flour, bound with hot oil and butter, then pressed through a brass mould by hand — every spiral is a slightly different size and we have stopped apologising for it. Ajwain and sesame in the dough, fried on a medium flame so the inside cooks before the outside colours.','Rice flour, roasted gram flour, sesame, ajwain, cumin, butter, asafoetida, chilli powder, salt, groundnut oil','30 days, airtight',169.00,NULL,'250 g','KR-SNK-002',70,1,TRUE,FALSE,TRUE,'/images/products/chakli.webp','["/images/products/chakli.webp", "/images/categories/snacks.webp"]','Tea, and someone else''s house',5.00,1),
(12,'Papad','papad',4,'Urad papad, sun-dried three days. Roast on a flame or fry — both work.','Urad dal flour worked with papad khar and black pepper, rolled thin by hand and dried on cloth on the terrace for three days. Roast it directly on a gas flame with tongs for twenty seconds a side, or deep-fry for five. Comes uncooked, twenty to a pack.','Urad dal flour, black pepper, cumin, asafoetida, papad khar, salt','6 months, dry and flat',119.00,NULL,'200 g / 20 pieces','KR-SNK-003',120,1,TRUE,FALSE,TRUE,'/images/products/papad.webp','["/images/products/papad.webp", "/images/categories/snacks.webp"]','Every single meal on this site',4.00,1),
(13,'Mysore Pak','mysore-pak',5,'The porous, ghee-drenched kind. Made to order, cut warm, never stocked.','Besan, sugar and an amount of ghee we would rather not print, beaten continuously until the mixture goes from smooth to grainy to full of air — the whole thing takes twenty minutes and cannot be left alone for any of them. This is the soft, honeycombed Mysore pak, not the dense fudge sold under the same name. Made after you order it.','Besan, sugar, cow ghee, cardamom','10 days. It is mostly ghee and sugar; it will not last that long.',329.00,NULL,'400 g box','KR-SWT-001',24,0,TRUE,TRUE,TRUE,'/images/products/mysore-pak.webp','["/images/products/mysore-pak.webp", "/images/categories/sweets.webp"]','Nothing. Do not dilute it.',5.00,1),
(14,'Puran Poli','puran-poli',5,'Chana dal and jaggery puran, rolled thin enough to see through. Four to a pack.','Chana dal cooked down with jaggery and cardamom into puran, stuffed into a soft maida-and-ghee dough and rolled out thin — thin enough that the filling shows through, which is the only test that matters. Griddled on both sides. Reheat on a tawa with ghee, never in a microwave, and eat with more ghee than you think is reasonable.','Chana dal, jaggery, maida, cardamom, nutmeg, cow ghee','5 days refrigerated',199.00,229.00,'Pack of 4','KR-SWT-002',30,0,TRUE,FALSE,TRUE,'/images/products/puran-poli.webp','["/images/products/puran-poli.webp", "/images/categories/sweets.webp"]','Warm milk, or a spoon of ghee melting on top',5.00,1);

INSERT INTO users (id,email,full_name,phone,hashed_password,is_active) VALUES
(1,'meera@example.com','Meera Ramanathan','+91 98450 11223','$2b$12$kfiBOQZf4ejKw//hJ42rTeNfySiy1ookS2idO1zsjXlM4itA4f9ku',TRUE),
(2,'arjun@example.com','Arjun Shetty','+91 99001 44556','$2b$12$Um7D2vaMbKxWUzO1Ui2Ubec7ElSPNsPqFTxQ59LnGkQBjoE33swlm',TRUE),
(3,'divya@example.com','Divya Krishnan','+91 90080 77661','$2b$12$wXzz0MD.zT1NLRKb/LU6weJchOj0ZGHSgpXpFgC3iS4HfcCoQnDVy',TRUE),
(4,'nikhil@example.com','Nikhil Rao','+91 98862 33445','$2b$12$XaCi8zs5GQtuy4msZo0GMODjWUNYSa5ZbN09AUQPO16aGmBMY9nRe',TRUE),
(5,'fatima@example.com','Fatima Sheikh','+91 97400 55882','$2b$12$ZbpR73uWhBLehk6qB/e1mejai3B35fvV/P0HkOzsgPdirdeSaTQp6',TRUE),
(6,'sandeep@example.com','Sandeep Gowda','+91 91082 66774','$2b$12$bEmTh1P/isjHNI5fHLtwvuhtDbi/EUR4cuKxXyKRZVMwiJ9S.8gEi',TRUE);

INSERT INTO reviews (id,product_id,user_id,rating,title,body,is_verified_purchase) VALUES
(1,1,1,5,'Tastes like Mangalore','I have bought four sukka masalas online and returned three. This one actually has roasted coconut in it — you can see it in the grind. Made kori sukka on Sunday and my mother asked which shop I got it from, which is the highest praise available in my family.',TRUE),
(2,1,2,5,'Three spoons is enough','Went in with my usual heavy hand and it was too much. Follow the instruction on the label. Genuinely strong stuff.',TRUE),
(3,1,4,4,NULL,'Excellent flavour. Clumped a bit in Bombay humidity but that is on the weather, not them. Broke it up with a fork and it was fine.',TRUE),
(4,5,3,5,'The stone is attached','Whoever cut these knew what they were doing — every piece has the stone still on it. Sharp and salty right now, and I am told it settles by month three. Already ordered a second jar to keep unopened.',TRUE),
(5,5,5,5,NULL,'Oil sits properly above the pieces, no shortcuts. Curd rice has been upgraded permanently.',TRUE),
(6,8,6,5,'Arrived cold and alive','Delivered chilled, still risen, smelled exactly right. First dosa was rubbish because my tawa was not hot enough; the next eleven were perfect. That one is my fault.',TRUE),
(7,8,1,4,'Order the day before','Great batter, just plan for it — four days is a real limit, not a suggestion. I now order it on Thursday for the weekend.',TRUE),
(8,4,3,5,'You need less than you think','Went in with two spoons out of habit and the sambar nearly walked out of the pot. One is plenty. The roasted dal makes it thick without any other help.',TRUE),
(9,10,2,5,'Pale gold, not brown','Fried in actual coconut oil, and you can tell from the smell when the bag opens. The 250 g lasted an evening, which is a complaint about me.',TRUE),
(10,13,5,5,'The soft kind','This is the porous ghee one, not the hard fudge everyone else ships. It took an extra day to arrive because they make it after you order and that is exactly the right trade.',TRUE),
(11,2,6,4,NULL,'Crust is legitimately good — the besan trick works. Marinate the full hour, do not rush it like I did the first time.',TRUE),
(12,11,4,5,'Snaps properly','Every one of them broke clean instead of bending. Sizes are all slightly different, which is how you know a machine did not make them.',TRUE),
(13,12,1,4,NULL,'Twenty in a pack, roasts on the flame in about fifteen seconds. Nothing surprising here, which is the point of a papad.',TRUE),
(14,6,3,5,'No oil at all','Exactly the type my grandmother made. Skins have gone soft and translucent, which only happens with real time in salt.',TRUE),
(15,14,2,5,'Rolled thin','You can see the puran through the dough. Reheated with ghee on a tawa as instructed. Four disappeared between two people.',TRUE),
(16,3,5,4,'Works on prawns too','Used it on bangda first, then prawns. The tamarind is what makes it — most fish masalas just add more chilli and hope.',TRUE);

SELECT setval(pg_get_serial_sequence('categories','id'), COALESCE((SELECT MAX(id) FROM categories),1));

SELECT setval(pg_get_serial_sequence('products','id'), COALESCE((SELECT MAX(id) FROM products),1));

SELECT setval(pg_get_serial_sequence('users','id'), COALESCE((SELECT MAX(id) FROM users),1));

SELECT setval(pg_get_serial_sequence('reviews','id'), COALESCE((SELECT MAX(id) FROM reviews),1));